apiVersion: v1
kind: Service
metadata:
  name: eks-app-suengineer
  namespace: eks-app-suengineer
  labels:
    app: eks-app-suengineer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-app-suengineer
